import { Pet, Task } from '../types';

export const samplePets: Pet[] = [
  {
    id: '1',
    name: 'Бобик',
    type: 'dog',
    breed: 'Лабрадор',
    age: 3,
    weight: 25,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Мурка',
    type: 'cat',
    breed: 'Сиамская',
    age: 2,
    weight: 4.5,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Кеша',
    type: 'bird',
    breed: 'Попугай',
    age: 1,
    weight: 0.3,
    createdAt: new Date('2024-03-10'),
  },
];

export const sampleTasks: Task[] = [
  {
    id: '1',
    petId: '1',
    title: 'Утреннее кормление',
    type: 'feeding',
    priority: 'high',
    scheduledTime: new Date(new Date().setHours(8, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '2',
    petId: '1',
    title: 'Вечернее кормление',
    type: 'feeding',
    priority: 'high',
    scheduledTime: new Date(new Date().setHours(18, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '3',
    petId: '1',
    title: 'Утренняя прогулка',
    type: 'walk',
    priority: 'medium',
    scheduledTime: new Date(new Date().setHours(7, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '4',
    petId: '1',
    title: 'Вечерняя прогулка',
    type: 'walk',
    priority: 'medium',
    scheduledTime: new Date(new Date().setHours(19, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '5',
    petId: '2',
    title: 'Кормление Мурки',
    type: 'feeding',
    priority: 'high',
    scheduledTime: new Date(new Date().setHours(9, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '6',
    petId: '2',
    title: 'Вечернее кормление Мурки',
    type: 'feeding',
    priority: 'high',
    scheduledTime: new Date(new Date().setHours(20, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '7',
    petId: '3',
    title: 'Кормление Кеши',
    type: 'feeding',
    priority: 'high',
    scheduledTime: new Date(new Date().setHours(10, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '8',
    petId: '1',
    title: 'Игра с мячиком',
    type: 'play',
    priority: 'low',
    scheduledTime: new Date(new Date().setHours(16, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '9',
    petId: '1',
    title: 'Лакомство',
    type: 'treat',
    priority: 'low',
    scheduledTime: new Date(new Date().setHours(12, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
  {
    id: '10',
    petId: '2',
    title: 'Игра с лазером',
    type: 'play',
    priority: 'low',
    scheduledTime: new Date(new Date().setHours(15, 0, 0, 0)),
    isRecurring: true,
    recurrencePattern: 'daily',
    createdAt: new Date(),
  },
];

// Функция для загрузки примерных данных
export const loadSampleData = () => {
  return {
    pets: samplePets,
    tasks: sampleTasks,
    taskLogs: [],
  };
};